title: Fraggle Rock
description: >
  This is fraggle rock and we're here to make a mother fucking mess.

# the subpath of your site, e.g. /blog/
baseurl: "" 

# the base hostname & protocol for your site
url: "http://fragglerocks.rocks" 

# build settings
markdown: kramdown

# social settings
twitter_username:
github_username:
